package com.github.marcosbelfastdev.erbium.core;

public enum Common {
    LOAD_ON_DEMAND,
    INTERACT_DELAY_BEFORE,
    RESOLVE_TIMEOUT,
    CORE_SELENIUM_IMPLICITLY_WAIT, // only used when the core Selenium webdriver is exposed
    RETRY_INTERVAL,
    HIGHLIGHT_ELEMENTS,
    HIGHLIGHT_DELAY_AFTER,
    HIGHLIGHT_STYLE,
    HIGHLIGHT_FRAMES,
    SCROLL_TO_ELEMENTS,
    SCROLL_DELAY_AFTER,
    REQUIRE_ENABLED,
    REQUIRE_VISIBLE,
    ENABLED_TIMEOUT,
    VISIBLE_TIMEOUT,
    EXECUTOR_CLICKS,
    EXECUTOR_SETTEXT,
    EXECUTOR_CLEAR,
    INTERACT_DELAY_AFTER,
	PAGE_LOAD_TIMEOUT,
    SUPPRESS_DELAYS,
    HANDLE_ALERTS,
    ALERTS_ACTION,
    SEARCHSCROLL_RESOLVE,
    SEARCHSCROLL_FACTOR,
    SEARCHSCROLL_HEIGHT,
    SEARCHSCROLL_TIMEOUT,
    FALLBACK_TO_EXECUTOR,
    WINDOW_LOCKING,
    WINDOW_SEARCH,
    HIDE_PASSWORDS,
    ENABLE_SCREENSHOTS,
    SCREEN_SIZE,
    SCREEN_POSITION,
    FULLSCREEN;


}
