package org.base.erbium;

public enum Reporting {
    REPORT_TO_TESTNG,
    LOG_TEST_STEPS,
    //LOG_PASSIVE_ACTIONS,
    LOG_OPTIONS,
    LOG_FRAMES,
    LOG_WINDOWS_ACTIONS,
    LOG_WINDOWS_DETAILS,
    LOG_CONDITIONS,
    LOG_DETAILED_CONDITIONS,
}